[package]
name = "build-inspector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "build-inspector"
path = "src/main.rs"

[dependencies]
cargo_metadata = "0.18.1"
clap = { version = "4.4.7", features = ["derive"] }
git2 = "0.18.1"
if_chain = "1.0.2"
semver = "1.0.20"
serde = "1.0.190"
serde_json = "1.0.108"
serde_derive = "1.0.190"
thiserror = "1.0.50"
toml = "0.8.6"
anyhow = "1.0.75"

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10.57", features = ["vendored"] }
libc = "0.2.150"
libgit2-sys = { version = "0.16.1", features = ["vendored"] }
curl = { version = "0.4.44", features = ["static-curl", "static-ssl"] }
git2-curl = "0.19.0"
curl-sys = "0.4.70"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "z"
strip = "debuginfo"
panic = "abort"
