[package]
name = "rust-buildcheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.18.1"
clap = { version = "4.4.7", features = ["derive"] }
git2 = "0.17.2"
thiserror = "1.0.50"

