#未在当前分支下读取到构建任务配置文件，您可在当前页面进行编辑，通过点击“保存并提交”按钮来新增。
---
version: 2.0

env:
  resource:
    type: "docker"
    image: ${build_image}
    class: 32U64G

#......, ...................
params:
  - name: product
    value: cloudbuild2.0

#....
steps:
  PRE_BUILD: # ......
    - checkout # 检出当前源码库
  BUILD: # ......
    - build_execute:
        command: sh ./cloudbuild/build.sh
        check: false
  POST_BUILD:
    - artget:
        artifact_type: cmcbinary #选填
        action: push
        dependency: dependency.xml
        agent: ${agentPath}
        params:
            version: ${version}
            source_path: ${source_path}
            dest_path: ${dest_path}
        username: ${cmcUsername}
        password: ${cmcPassword}